"""add unblock_until_field in deal table

Revision ID: 1bf32561106d
Revises: 9229d43c4f24
Create Date: 2025-07-18 10:36:26.613585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bf32561106d'
down_revision: Union[str, None] = '9229d43c4f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('admin_decision', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('admin_reason', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('admin_id', sa.BigInteger(), nullable=True))
    op.add_column('deals', sa.Column('time_extension', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('time_extension_until', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'deals', 'users', ['admin_id'], ['tg_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_column('deals', 'time_extension_until')
    op.drop_column('deals', 'time_extension')
    op.drop_column('deals', 'admin_id')
    op.drop_column('deals', 'admin_reason')
    op.drop_column('deals', 'admin_decision')
    # ### end Alembic commands ###
