"""add five_photos_column in product table

Revision ID: 2a8312dd1ea7
Revises: b77c6b03b920
Create Date: 2025-07-09 22:44:21.366357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a8312dd1ea7'
down_revision: Union[str, None] = 'b77c6b03b920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('additional_images', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('products_product_image_url_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_product_image_url_key'), 'products', ['product_image_url'], postgresql_nulls_not_distinct=False)
    op.drop_column('products', 'additional_images')
    # ### end Alembic commands ###
