"""del username field in product table

Revision ID: 2e88e780dc58
Revises: acc47256b72c
Create Date: 2025-06-02 21:03:17.672378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e88e780dc58'
down_revision: Union[str, None] = 'acc47256b72c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_username_fkey'), 'products', type_='foreignkey')
    op.drop_column('products', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('products_username_fkey'), 'products', 'users', ['username'], ['username'])
    # ### end Alembic commands ###
