"""add cascade delete

Revision ID: 3c1217a52a67
Revises: f8c6373abedb
Create Date: 2025-06-17 13:52:37.136964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c1217a52a67'
down_revision: Union[str, None] = 'f8c6373abedb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favs_tg_id_fkey'), 'favs', type_='foreignkey')
    op.create_foreign_key(None, 'favs', 'users', ['tg_id'], ['tg_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('products_tg_id_fkey'), 'products', type_='foreignkey')
    op.drop_constraint(op.f('products_category_name_fkey'), 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['tg_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'products', 'categories', ['category_name'], ['category_name'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key(op.f('products_category_name_fkey'), 'products', 'categories', ['category_name'], ['category_name'])
    op.create_foreign_key(op.f('products_tg_id_fkey'), 'products', 'users', ['tg_id'], ['tg_id'])
    op.drop_constraint(None, 'favs', type_='foreignkey')
    op.create_foreign_key(op.f('favs_tg_id_fkey'), 'favs', 'users', ['tg_id'], ['tg_id'])
    # ### end Alembic commands ###
