"""add user token field

Revision ID: 4529c9cbeff5
Revises: 74656bce4875
Create Date: 2025-05-28 21:35:46.156950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4529c9cbeff5'
down_revision: Union[str, None] = '74656bce4875'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['tg_id'])
    op.create_unique_constraint(None, 'users', ['token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'token')
    # ### end Alembic commands ###
