"""update deal table edit integer to biginteger

Revision ID: 5549147cc9fd
Revises: f0302e3c1533
Create Date: 2025-07-14 14:01:29.219247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5549147cc9fd'
down_revision: Union[str, None] = 'f0302e3c1533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('deals', 'seller_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('deals', 'buyer_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_foreign_key(None, 'deals', 'users', ['seller_id'], ['tg_id'])
    op.create_foreign_key(None, 'deals', 'users', ['buyer_id'], ['tg_id'])
    op.drop_column('deals', 'buyer_review')
    op.drop_column('deals', 'admin_comment')
    op.drop_column('deals', 'buyer_rating')
    op.drop_column('deals', 'currency')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('buyer_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('admin_comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deals', sa.Column('buyer_review', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.alter_column('deals', 'buyer_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('deals', 'seller_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
