"""update deal table add currency field

Revision ID: 5dbcb1737c95
Revises: 5549147cc9fd
Create Date: 2025-07-14 14:12:07.120354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5dbcb1737c95'
down_revision: Union[str, None] = '5549147cc9fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'currency')
    # ### end Alembic commands ###
