"""add rub collateral_amount in deal table

Revision ID: 6563e01a9763
Revises: 4a60cada1180
Create Date: 2025-09-27 22:40:53.519561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6563e01a9763'
down_revision: Union[str, None] = '4a60cada1180'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('rub_payment_confirmed', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('collateral_amount', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'collateral_amount')
    op.drop_column('deals', 'rub_payment_confirmed')
    # ### end Alembic commands ###
