"""add cascade delete in more field

Revision ID: 75c072ce7cfb
Revises: 2f18da3b378d
Create Date: 2025-06-24 06:24:42.734109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75c072ce7cfb'
down_revision: Union[str, None] = '2f18da3b378d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('favs_product_id_fkey'), 'favs', type_='foreignkey')
    op.create_foreign_key(None, 'favs', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('messages_chat_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_receiver_id_fkey'), 'messages', type_='foreignkey')
    op.drop_constraint(op.f('messages_sender_id_fkey'), 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['receiver_id'], ['tg_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'messages', 'users', ['sender_id'], ['tg_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key(op.f('messages_sender_id_fkey'), 'messages', 'users', ['sender_id'], ['tg_id'])
    op.create_foreign_key(op.f('messages_receiver_id_fkey'), 'messages', 'users', ['receiver_id'], ['tg_id'])
    op.create_foreign_key(op.f('messages_chat_id_fkey'), 'messages', 'chats', ['chat_id'], ['id'])
    op.drop_constraint(None, 'favs', type_='foreignkey')
    op.create_foreign_key(op.f('favs_product_id_fkey'), 'favs', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
