"""add reserve fields in product table

Revision ID: 7f9d9f3a4ee8
Revises: 1bf32561106d
Create Date: 2025-07-22 07:02:34.114583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9d9f3a4ee8'
down_revision: Union[str, None] = '1bf32561106d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('reserved', sa.Boolean(), nullable=True))
    op.add_column('products', sa.Column('reserved_until', sa.DateTime(timezone=True), nullable=True))
    op.add_column('products', sa.Column('reserved_by', sa.BigInteger(), nullable=True))
    op.add_column('products', sa.Column('reservation_amount', sa.Float(), nullable=True))
    op.add_column('products', sa.Column('reservation_currency', sa.String(), nullable=True))
    op.create_foreign_key(None, 'products', 'users', ['reserved_by'], ['tg_id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'reservation_currency')
    op.drop_column('products', 'reservation_amount')
    op.drop_column('products', 'reserved_by')
    op.drop_column('products', 'reserved_until')
    op.drop_column('products', 'reserved')
    # ### end Alembic commands ###
