"""del rub

Revision ID: 86e55b0cf01e
Revises: 9e095d0dd927
Create Date: 2025-09-27 15:59:33.373474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86e55b0cf01e'
down_revision: Union[str, None] = '9e095d0dd927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'earned_rub')
    op.drop_column('users', 'current_currency')
    op.drop_column('users', 'rub_balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rub_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('current_currency', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('earned_rub', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
