"""edit products add more photos

Revision ID: 8dbd7a7ebfb1
Revises: 6fe9f90c60ac
Create Date: 2025-07-29 09:03:55.594435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbd7a7ebfb1'
down_revision: Union[str, None] = '6fe9f90c60ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_product_image_url_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_product_image_url_key'), 'products', ['product_image_url'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
