"""add cancel fields in deal table

Revision ID: a355d90f7378
Revises: 6e2a00c39313
Create Date: 2025-07-15 11:22:35.626505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a355d90f7378'
down_revision: Union[str, None] = '6e2a00c39313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('pending_cancel', sa.Boolean(), nullable=True))
    op.add_column('deals', sa.Column('cancel_reason', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('cancel_request_by', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'cancel_request_by')
    op.drop_column('deals', 'cancel_reason')
    op.drop_column('deals', 'pending_cancel')
    # ### end Alembic commands ###
