"""add plus_minus rep field in user table

Revision ID: a4f51ab87a26
Revises: 93ff96b852d7
Create Date: 2025-06-19 13:23:42.244381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f51ab87a26'
down_revision: Union[str, None] = '93ff96b852d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plus_rep', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('minus_rep', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'minus_rep')
    op.drop_column('users', 'plus_rep')
    # ### end Alembic commands ###
