"""update user table and add ton_rub balance

Revision ID: b77c6b03b920
Revises: 755a63569d67
Create Date: 2025-06-30 09:21:08.773669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b77c6b03b920'
down_revision: Union[str, None] = '755a63569d67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('rub_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('ton_balance', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('current_currency', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'current_currency')
    op.drop_column('users', 'ton_balance')
    op.drop_column('users', 'rub_balance')
    # ### end Alembic commands ###
