"""edit deal table

Revision ID: c43ebc3fccbc
Revises: c7e90b85b0aa
Create Date: 2025-08-22 08:15:25.893653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c43ebc3fccbc'
down_revision: Union[str, None] = 'c7e90b85b0aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('deals_product_id_fkey'), 'deals', type_='foreignkey')
    op.create_foreign_key(None, 'deals', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'deals', type_='foreignkey')
    op.create_foreign_key(op.f('deals_product_id_fkey'), 'deals', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###
