"""update deal table

Revision ID: f0302e3c1533
Revises: e24802ab45a1
Create Date: 2025-07-14 12:58:32.467851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0302e3c1533'
down_revision: Union[str, None] = 'e24802ab45a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deals', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('buyer_review', sa.String(), nullable=True))
    op.add_column('deals', sa.Column('buyer_rating', sa.Integer(), nullable=True))
    op.add_column('deals', sa.Column('admin_comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deals', 'admin_comment')
    op.drop_column('deals', 'buyer_rating')
    op.drop_column('deals', 'buyer_review')
    op.drop_column('deals', 'currency')
    # ### end Alembic commands ###
